### ISSUE TITLE
Images should be clickable too

### ISSUE THREAD

**Issue by Kaushik-Iyer** [lovishprabhakar/C-Simplify#10]
Clicking on the title leads to different pages, It should be the same for clicking on the image too. I can work on this if it goes under hacktoberfest

**Comment by arishmaurya** [comment]
@Kaushik-Iyer i want to work on this please assign it to me

**Comment by lovishprabhakar** [comment]
Go ahead @Kaushik-Iyer!

**Comment by lovishprabhakar** [comment]
> @Kaushik-Iyer i want to work on this please assign it to me

@arishmaurya sorry, since this issue was opened by @Kaushik-Iyer, he is the one who will get to work on it. If you have any other improvements you can open an issue of your own and it will be assigned to you :)
