### ISSUE TITLE
A simple note taking app

### ISSUE THREAD

**Issue by Welf06** [lovishprabhakar/C-Simplify#12]
> Can add and delete notes
> Can edit the notes

**Comment by Welf06** [comment]
If this issue is approved, I hope it will be assigned to me : )

**Comment by lovishprabhakar** [comment]
Go ahead @Welf06!

**Comment by Welf06** [comment]
The hosted website is different from what I am getting locally
![image](https://user-images.githubusercontent.com/85446331/193415055-ce5d308e-cb3d-4099-a9b3-f33eba218b9d.png)
The images aren't loading and there are only 6 cards as compared to the 8 cards in the hosted website
I think the issue is with unplash API.
Please help me out on how to proceed ahead

**Comment by Welf06** [comment]
For now I will just copy the format of other cards in index.html and home.js

**Comment by Welf06** [comment]
I have sent a pr with the notes taking app
hope you like it : )
please don't forget to put the right label for the PR ❇️
