### ISSUE TITLE
Need margin adjustment between quote and navbar and also footer to be added

### ISSUE THREAD

**Issue by raunak-dev-edu** [lovishprabhakar/C-Simplify#13]
In my opinion, some modifications in the margin can improve the look of the home page. Also, I want to add a footer to this.

**Comment by lovishprabhakar** [comment]
@raunak-dev-edu footer is being added by some other contributor, but you can go for the gap between nav and quote!

**Comment by raunak-dev-edu** [comment]
> @raunak-dev-edu footer is being added by some other contributor, but you can go for the gap between nav and quote!

ok and thank you
