### ISSUE TITLE
Add Preloader Feature

### ISSUE THREAD

**Issue by akhil-aggarwal** [lovishprabhakar/C-Simplify#23]
**Is your feature request related to a problem? Please describe.**
Lets just say it, Preloader are awesome!

**Describe the solution you'd like**
A sick looking preloader that goes along with the theme of the website.

**Describe alternatives you've considered**
Would also love to add a favicon for the website.

**Additional context**
I would love to contribute more to the open source community as a part of hacktober fest

**Comment by lovishprabhakar** [comment]
Go ahead @akhil-aggarwal!
