### ISSUE TITLE
Design improvements in dictionary.html page 

### ISSUE THREAD

**Issue by Phoenix-031** [lovishprabhakar/C-Simplify#3]
search word and buttons are not spaced properly i would like to improve the look

**Comment by TheInspiredConjurer** [comment]
I would like to work on this.

**Comment by Phoenix-031** [comment]
i would request you to assign it to me as a part of hacktoberfest contributions

**Comment by lovishprabhakar** [comment]
Go ahead @Phoenix-031!

**Comment by lovishprabhakar** [comment]
Don't forget to star the repository! @Phoenix-031
