### ISSUE TITLE
Improve the search section in Post Index Number pge

### ISSUE THREAD

**Issue by surya-doc** [lovishprabhakar/C-Simplify#31]
![Screenshot 2022-10-02 083609](https://user-images.githubusercontent.com/69008196/193436118-22912c4a-b910-466a-bac8-6f8c05d0064c.png)
* The search by dropdown and the search input section are together which makes it a bit confusing to the user. Want to work on it.

**Comment by lovishprabhakar** [comment]
Go ahead! @surya-doc

**Comment by lovishprabhakar** [comment]
Don't forget to star the repository :)

**Comment by surya-doc** [comment]
Sure.
