### ISSUE TITLE
Adding Custom Gradient ScrollBar

### ISSUE THREAD

**Issue by aakashraj01** [lovishprabhakar/C-Simplify#38]
Hey @lovishprabhakar . I want to add custom gradient color scrollbar using CSS3 on this website  . Would love to contribute in this project and repo. Can you please assign it to me under Hacktoberfest'22 accepted

**Comment by lovishprabhakar** [comment]
Go ahead @aakashraj01!

**Comment by lovishprabhakar** [comment]
Don't forget to star the repository :)

**Comment by aakashraj01** [comment]
Hey @lovishprabhakar I have created the PR for this issue and added the feature. Please review and merge it :)
