### ISSUE TITLE
Navbar Improvements and Footer redesign

### ISSUE THREAD

**Issue by TheInspiredConjurer** [lovishprabhakar/C-Simplify#4]
- The search bar is way too small.
- The footer needs to be at the bottom of the page, not the top.

I would like to work on this as part of hacktoberfest.

**Comment by lovishprabhakar** [comment]
Go ahead! @TheInspiredConjurer

**Comment by lovishprabhakar** [comment]
Don't forget to star the repository!

**Comment by TheInspiredConjurer** [comment]
Done!

**Comment by lovishprabhakar** [comment]
@TheInspiredConjurer updates?

**Comment by lovishprabhakar** [comment]
@TheInspiredConjurer as the deadline for solving the issue is 3 days after it was opened, this issue will be closed at the end of today if you don't show any activity.

**Comment by TheInspiredConjurer** [comment]
@lovishprabhakar okay, I will submit it by today
