### ISSUE TITLE
Enhancing Header and designing footer

### ISSUE THREAD

**Issue by THE-AryanKumar** [lovishprabhakar/C-Simplify#49]
- Improve the navbar and add shortcuts to it with a Dark-Mode toggle.
- Bring the footer to its original place.
- Make the Header responsive with hamburger menu dropdown

@jailbreakerVC Can you /assign me. I want to work on this.

**Comment by lovishprabhakar** [comment]
Go ahead @THE-AryanKumar!
You can also get the issue assigned to you by commenting `\assign`.
Don't forget to star the repository!

**Comment by lovishprabhakar** [comment]
Will you be adding dark mode as well or just a toggle? @THE-AryanKumar

**Comment by THE-AryanKumar** [comment]
I'll add the working Dark-Mode

**Comment by THE-AryanKumar** [comment]
@lovishprabhakar please review the work. Thank You

**Comment by THE-AryanKumar** [comment]
![Screenshot 2022-10-03 043813](https://user-images.githubusercontent.com/97040203/193480395-fd89ed51-f5db-475f-8c3e-71a00d0e174c.jpg)
I don't understand what is this. Also it is showing Not-accepted

**Comment by lovishprabhakar** [comment]
@THE-AryanKumar don't worry about the failed check, it is a server issue. Where does it show not accepted?

**Comment by lovishprabhakar** [comment]
Now that your PR is merged it won't be showing not-accepted on the website anymore :)
