### ISSUE TITLE
Adding Color Palette Generator Card

### ISSUE THREAD

**Issue by lovishprabhakar** [lovishprabhakar/C-Simplify#55]
This issue is open for anyone to work on. You just need to add a card for a Random Color Palette Generator on the home page (index.html). The CSS and JS files for it have already been added, just need to add a card on the home page.

**Comment by Kirti36** [comment]
assign this to me...

**Comment by lovishprabhakar** [comment]
@achiverram28 @Kirti36 are you working on this? Please provide some updates.

**Comment by bharathmb7** [comment]
@lovishprabhakar i think you can close this issue has it is completed.

**Comment by lovishprabhakar** [comment]
@bharathmb7 definitely. Thanks for reminding
