### ISSUE TITLE
Missing Card Animation 

### ISSUE THREAD

**Issue by hs-07** [lovishprabhakar/C-Simplify#58]
I went through the website and want to raid this issue, that when we hover over the cards, they just pop out suddenly which provide less attractive UX.
So, I want to work to enhance the animations of cards and other small details.
@lovishprabhakar

**Comment by lovishprabhakar** [comment]
Go ahead @hs-07!

**Comment by lovishprabhakar** [comment]
@hs-07 updates?

**Comment by hs-07** [comment]
@lovishprabhakar 
yaa , just working over the  issue, got stuck in some other stuffs.

**Comment by hs-07** [comment]
PR Made , 
kindly have a look and ping me if any changes required. @lovishprabhakar
