### ISSUE TITLE
Un-necessary Button Action.

### ISSUE THREAD

**Issue by rahul-n18** [lovishprabhakar/C-Simplify#63]
Either this button needs to be changed or just keep it as Dummy button.
Because already search bar gives you suggestion.

![Screenshot (43)](https://user-images.githubusercontent.com/64891042/193515481-1d8d1382-a7de-423c-b6e4-15c56cc49f91.png)

![Screenshot (44)](https://user-images.githubusercontent.com/64891042/193515484-1cdcef07-8475-4794-bd28-309464832a5a.png)

**Comment by rahul-n18** [comment]
Sure thing,
I was waiting for your message

**Comment by lovishprabhakar** [comment]
Apologies for the delay :)
Don't forget to star the repository!

**Comment by rahul-n18** [comment]
yes ill do that

**Comment by lovishprabhakar** [comment]
@rahul-n18 please remove the dark mode toggle as well as it doesn't do anything.
