### ISSUE TITLE
Images are not Loading 

### ISSUE THREAD

**Issue by Manish5121** [lovishprabhakar/C-Simplify#7]
-i would like to try resloving this issue.

![2022-10-01 (4)](https://user-images.githubusercontent.com/94914243/193413397-d15fb2a3-e2ff-465f-8579-96a2dd33a532.png)

**Comment by lovishprabhakar** [comment]
Didn't notice that error, Go for it @Manish5121!

**Comment by Manish5121** [comment]
hey @lovishprabhakar 
-
https://lovishprabhakar.github.io/CSimplify/Code/index.html
This is the link that you put on Hacktoberfest discord server which is working completely fine 

and 
https://lovishprabhakar.github.io/C-Simplify/Code/index.html 
This is the link which you've placed onto this repo about section and readme which have that image not loading issue 

so i think there is no issue in code 
-correct me if am wrong I'm just new to open source

**Comment by lovishprabhakar** [comment]
Yeah, great catch @Manish5121. The link shared on Discord is wrong actually, as it was a previous deployment. I had to create a new repository for hacktoberfest, which is this one. I'll correct the discord link while you can try to solve the loading issue here.

**Comment by Manish5121** [comment]
hey  @lovishprabhakar  the `src` attribute is missing in html tag which is creating this error.
![2022-10-01 (5)](https://user-images.githubusercontent.com/94914243/193414992-73ee6455-f051-4512-b8a2-7096a42c084e.png)

**Comment by lovishprabhakar** [comment]
@Manish5121 the error was not due to that, it was more of a server-side bug. It has been fixed now so I'm closing this issue. If you have any other suggestions you are very welcome to contribute :)
