### ISSUE TITLE
Want to add Share buttons so that user can easily share your website at different social media

### ISSUE THREAD

**Issue by grraghav120** [lovishprabhakar/C-Simplify#97]
Want to add Share buttons so that user can easily share your website at different social media 

User Friendly Feature

**Comment by grraghav120** [comment]
!assign

**Comment by grraghav120** [comment]
Any suggestions for new features? @maintainers

**Comment by lovishprabhakar** [comment]
Go ahead @grraghav120! Do share the screenshot when you create PR so that I can suggest changes if necessary.
About new features, whenever I get an idea I create an open-for-all issue so you can look for that :)
For now, just work on the share button :) Don't forget to star the repository!
